import type { TrustDocument } from "@/content/trust/types";

/**
 * Terms — frame 1m. Deliberately short and unhedged: the product makes few
 * promises, and the ones it does make are the same ones the interface makes.
 */
export const termsDocument: TrustDocument = {
  slug: "terms",
  navLabel: "Terms",
  title: "Terms of use",
  description:
    "What Coding Journal offers, what it does not promise, and the conditions of using the hosted service.",
  lede: "Coding Journal is a personal journal of your own GitHub activity, offered as-is. These terms are short because the service asks little of you and promises little in return.",
  lastUpdated: "1 September 2026",
  sections: [
    {
      id: "the-service",
      heading: "What the service is",
      blocks: [
        {
          kind: "paragraph",
          text: "Coding Journal reads your GitHub activity through permissions you grant, and renders it as a private daily record with an optional AI summary. It is a single-person product: there is no sharing, no team view and no export of anyone else's work.",
        },
        {
          kind: "paragraph",
          text: "An account is your GitHub account. You are responsible for the security of that account and for the repository access you choose to grant.",
        },
      ],
    },
    {
      id: "acceptable-use",
      heading: "Acceptable use",
      blocks: [
        {
          kind: "list",
          items: [
            "Use the service for your own activity, through the interface it provides.",
            "Do not attempt to reach another person's journal, or to use the service to circumvent GitHub's own access controls.",
            "Do not automate the service beyond ordinary use. Requests are rate-limited per person and product-wide; a refusal says what still works and when it returns.",
            "Do not attempt to disrupt the service or its providers.",
          ],
        },
      ],
    },
    {
      id: "no-warranty",
      heading: "Availability and completeness",
      blocks: [
        {
          kind: "paragraph",
          text: "The service is provided as-is and as-available, without warranty of any kind. It depends on GitHub, Neon, Vercel and — for narratives only — OpenAI, and it will be unavailable or incomplete when they are.",
        },
        {
          kind: "paragraph",
          text: "Coding Journal is explicitly not a complete or authoritative record of your work, and must not be relied on as one. It records what the access you granted allows it to see, states its own limits on every day, and is not a system of record for performance review, compensation, compliance, or any legal or contractual purpose. Where the journal and GitHub disagree, GitHub is correct.",
        },
        {
          kind: "paragraph",
          text: "There is no backup you can restore from and no service level. Activity older than 30 days is deleted on purpose, and once deleted it is gone.",
        },
      ],
    },
    {
      id: "ai-summaries",
      heading: "AI summaries",
      blocks: [
        {
          kind: "paragraph",
          text: "Narratives are generated by a language model, validated against the day's own evidence, and shown read-only. They can still be wrong, and they are never a substitute for the recorded activity underneath them, which is the actual record. Narratives are optional, quota-bounded, and may be paused service-wide without notice.",
        },
      ],
    },
    {
      id: "ending-use",
      heading: "Ending your use",
      blocks: [
        {
          kind: "paragraph",
          text: "You can withdraw repository access on GitHub at any time, and delete your account from Settings at any time. Deletion is immediate, irreversible and complete.",
        },
        {
          kind: "paragraph",
          text: "The operator may suspend or end an account that is being used to attack the service or another person, and may discontinue the hosted service. Because Coding Journal is open source under the MIT License, you can always run your own instance.",
        },
      ],
    },
    {
      id: "liability",
      heading: "Liability and changes",
      blocks: [
        {
          kind: "paragraph",
          text: "To the fullest extent permitted by law, the operator is not liable for lost data, lost profits, or any indirect or consequential damages arising from use of the service. Nothing here limits liability that cannot lawfully be limited.",
        },
        {
          kind: "paragraph",
          text: "These terms carry the date they were last changed, and every change is visible in the repository's public history. Continuing to use the service after a change means accepting it.",
        },
      ],
    },
  ],
};
